# Generated by Django 5.2.6 on 2025-09-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
